---
- name: start awx services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - awx-cbreceiver
    - awx-dispatcher
    - awx-channels-worker
    - awx-daphne
    - awx-web

- name: enable awx services
  service:
    name: "{{ item }}"
    state: enabled
  with_items:
    - awx-cbreceiver
    - awx-dispatcher
    - awx-channels-worker
    - awx-daphne
    - awx-web

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: enable nginx
  service:
    name: nginx
    state: enabled

- name: restart memcached
  service:
    name: nginx
    state: restarted

- name: enable memcached
  service:
    name: nginx
    state: enabled

- name: restart postgresql
  service:
    name: nginx
    state: restarted

- name: enable postgresql
  service:
    name: nginx
    state: enabled

- name: restart rabbitmq
  service:
    name: nginx
    state: restarted

- name: enable rabbitmq
  service:
    name: nginx
    state: enabled