---
- name: Install prerequisite packages
  yum:
    name:
      - nginx
      - epel-release
      - memcached
      - ansible
    state: present
    notify:
     - enable memcached
     - enable nginx


- name: Setting up PostgresSQL 10 repository
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.3-x86_64/pgdg-redhat10-10-2.noarch.rpm"
    state: present

- name: Installing postgres 10
  yum:
    name:
      - postgresql10
      - postgresql10-server
      - postgresql10-contrib
      - postgresql10-libs
    state: present

- name: Initializing PosgresSQL
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
  notify:
    - restart postgresql
    - enable postgresql

- name: Create AWX Database
  postgresql_db:
    name: awx

- name: Create  DB User and Grant access to AWX 
  postgresql_user:
    db: awx
    name: awx

- name: Install Erlang Repo
  yum:
    name: "https://github.com/rabbitmq/erlang-rpm/releases/download/v21.3.7/erlang-21.3.7-1.el7.x86_64.rpm"

- name: Create RabbitMQ Repo 
  template:
    src: rabbitmq-erlang.repo.j2
    dest: /etc/yum.repos.d/rabbitmq-erlang.repo

- name: Install RabbitMQ
  yum:
    name: "https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.5/rabbitmq-server-3.7.5-1.el7.noarch.rpm"
    state: present
    notify:
    - restart rabbitmq
    - enable rabbitmq

- name: Copy NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    notify: restart nginx

- name: Create AWX Repo 
  template:
    src: awx-rpm.j2
    dest: /etc/yum.repos.d/rawx-rpm.repo

- name: Install AWX
  yum:
    name: awx

- name: Import AWX Database data
  shell: sudo -u awx /opt/awx/bin/awx-manage migrate

- name: Create AWX web access User
  shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | sudo -u awx /opt/awx/bin/awx-manage shell

- name: Initialize AWX
  shell: sudo -u awx /opt/awx/bin/awx-manage create_preload_data && sudo -u awx /opt/awx/bin/awx-manage provision_instance --hostname=$(hostname) && sudo -u awx /opt/awx/bin/awx-manage register_queue --queuename=tower --hostnames=$(hostname)
  notify:
    - start awx services
    - enable awx services